### ISSUE TITLE
cornerRadius not working on BHPhotoView

### ISSUE THREAD

**Issue by ShadowParticle** [benhurott/BHPhotoView#1]
I have tried this in the ViewDidLoad,
self. "BHPhotoView" .layer.cornerRadius = 20, but nothing happens.
I have even tried putting the BHPhotoView in a UIView, and using the ".layer.cornerRadius = 20" on the supView still not working.
I have also tried to trigger it in a n button action, but no use.

Am I doing something wrong or is it not possible to use cornerRadius on BHPhotoView?
Please help😩

**Comment by bhrott** [comment]
Hi!
Did you try to set in the inner layers?
Read this [DOCS](https://github.com/benhurott/BHPhotoView/blob/master/docs/ADVANCED.md#exposed-properties)

Let me know if the issue persists, ok?

Thanks, =).

**Comment by ShadowParticle** [comment]
@benhurott thank you for the quick response!
I solved it by adding; `BHPhotoView.layer.masksToBounds = true`

Regards
Marcus
